package com.cesgroup.prison.label.entity;

import java.util.Date;

import com.cesgroup.framework.base.entity.StringIDEntity;

public class Label extends StringIDEntity{
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_CUS_NUMBER
     *
     * @mbggenerated
     */
    private String mliCusNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_AREA_ID
     *
     * @mbggenerated
     */
    private String mliAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_WIDTH
     *
     * @mbggenerated
     */
    private Double mliWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_HEIGHT
     *
     * @mbggenerated
     */
    private Double mliHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_X
     *
     * @mbggenerated
     */
    private Double mliX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_Y
     *
     * @mbggenerated
     */
    private Double mliY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_Z
     *
     * @mbggenerated
     */
    private Double mliZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI__CRTE_USER_ID
     *
     * @mbggenerated
     */
    private String mliCrteUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_CRTE_TIME
     *
     * @mbggenerated
     */
    private Date mliCrteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_UPDT_TIME
     *
     * @mbggenerated
     */
    private Date mliUpdtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_UPDT_USER_ID
     *
     * @mbggenerated
     */
    private String mliUpdtUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_LABEL_CODE
     *
     * @mbggenerated
     */
    private String mliLabelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_MESSAGE_LABEL_INFO.MLI_LABEL_TYPE
     * 1.民警信息    2.罪犯信息     3.设备信息
     * @mbggenerated
     */
    private Integer mliLabelType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.ID
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.ID
     *
     * @mbggenerated
     */
    
    private String mliAreaName;
    
    
    public String getMliAreaName() {
		return mliAreaName;
	}

	public void setMliAreaName(String mliAreaName) {
		this.mliAreaName = mliAreaName;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.ID
     *
     * @param id the value for CDS_MESSAGE_LABEL_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_CUS_NUMBER
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_CUS_NUMBER
     *
     * @mbggenerated
     */
    public String getMliCusNumber() {
        return mliCusNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_CUS_NUMBER
     *
     * @param mliCusNumber the value for CDS_MESSAGE_LABEL_INFO.MLI_CUS_NUMBER
     *
     * @mbggenerated
     */
    public void setMliCusNumber(String mliCusNumber) {
        this.mliCusNumber = mliCusNumber == null ? null : mliCusNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_AREA_ID
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_AREA_ID
     *
     * @mbggenerated
     */
    public String getMliAreaId() {
        return mliAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_AREA_ID
     *
     * @param mliAreaId the value for CDS_MESSAGE_LABEL_INFO.MLI_AREA_ID
     *
     * @mbggenerated
     */
    public void setMliAreaId(String mliAreaId) {
        this.mliAreaId = mliAreaId == null ? null : mliAreaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_WIDTH
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_WIDTH
     *
     * @mbggenerated
     */
    public Double getMliWidth() {
        return mliWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_WIDTH
     *
     * @param mliWidth the value for CDS_MESSAGE_LABEL_INFO.MLI_WIDTH
     *
     * @mbggenerated
     */
    public void setMliWidth(Double mliWidth) {
        this.mliWidth = mliWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_HEIGHT
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_HEIGHT
     *
     * @mbggenerated
     */
    public Double getMliHeight() {
        return mliHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_HEIGHT
     *
     * @param mliHeight the value for CDS_MESSAGE_LABEL_INFO.MLI_HEIGHT
     *
     * @mbggenerated
     */
    public void setMliHeight(Double mliHeight) {
        this.mliHeight = mliHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_X
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_X
     *
     * @mbggenerated
     */
    public Double getMliX() {
        return mliX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_X
     *
     * @param mliX the value for CDS_MESSAGE_LABEL_INFO.MLI_X
     *
     * @mbggenerated
     */
    public void setMliX(Double mliX) {
        this.mliX = mliX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_Y
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_Y
     *
     * @mbggenerated
     */
    public Double getMliY() {
        return mliY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_Y
     *
     * @param mliY the value for CDS_MESSAGE_LABEL_INFO.MLI_Y
     *
     * @mbggenerated
     */
    public void setMliY(Double mliY) {
        this.mliY = mliY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_Z
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_Z
     *
     * @mbggenerated
     */
    public Double getMliZ() {
        return mliZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_Z
     *
     * @param mliZ the value for CDS_MESSAGE_LABEL_INFO.MLI_Z
     *
     * @mbggenerated
     */
    public void setMliZ(Double mliZ) {
        this.mliZ = mliZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI__CRTE_USER_ID
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI__CRTE_USER_ID
     *
     * @mbggenerated
     */
    public String getMliCrteUserId() {
        return mliCrteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI__CRTE_USER_ID
     *
     * @param mliCrteUserId the value for CDS_MESSAGE_LABEL_INFO.MLI__CRTE_USER_ID
     *
     * @mbggenerated
     */
    public void setMliCrteUserId(String mliCrteUserId) {
        this.mliCrteUserId = mliCrteUserId == null ? null : mliCrteUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_CRTE_TIME
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_CRTE_TIME
     *
     * @mbggenerated
     */
    public Date getMliCrteTime() {
        return mliCrteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_CRTE_TIME
     *
     * @param mliCrteTime the value for CDS_MESSAGE_LABEL_INFO.MLI_CRTE_TIME
     *
     * @mbggenerated
     */
    public void setMliCrteTime(Date mliCrteTime) {
        this.mliCrteTime = mliCrteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_UPDT_TIME
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_UPDT_TIME
     *
     * @mbggenerated
     */
    public Date getMliUpdtTime() {
        return mliUpdtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_UPDT_TIME
     *
     * @param mliUpdtTime the value for CDS_MESSAGE_LABEL_INFO.MLI_UPDT_TIME
     *
     * @mbggenerated
     */
    public void setMliUpdtTime(Date mliUpdtTime) {
        this.mliUpdtTime = mliUpdtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_UPDT_USER_ID
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_UPDT_USER_ID
     *
     * @mbggenerated
     */
    public String getMliUpdtUserId() {
        return mliUpdtUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_UPDT_USER_ID
     *
     * @param mliUpdtUserId the value for CDS_MESSAGE_LABEL_INFO.MLI_UPDT_USER_ID
     *
     * @mbggenerated
     */
    public void setMliUpdtUserId(String mliUpdtUserId) {
        this.mliUpdtUserId = mliUpdtUserId == null ? null : mliUpdtUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_LABEL_CODE
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_LABEL_CODE
     *
     * @mbggenerated
     */
    public String getMliLabelCode() {
        return mliLabelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_LABEL_CODE
     *
     * @param mliLabelCode the value for CDS_MESSAGE_LABEL_INFO.MLI_LABEL_CODE
     *
     * @mbggenerated
     */
    public void setMliLabelCode(String mliLabelCode) {
        this.mliLabelCode = mliLabelCode == null ? null : mliLabelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_LABEL_TYPE
     *
     * @return the value of CDS_MESSAGE_LABEL_INFO.MLI_LABEL_TYPE
     *
     * @mbggenerated
     */
    public Integer getMliLabelType() {
        return mliLabelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_MESSAGE_LABEL_INFO.MLI_LABEL_TYPE
     *
     * @param mliLabelType the value for CDS_MESSAGE_LABEL_INFO.MLI_LABEL_TYPE
     *
     * @mbggenerated
     */
    public void setMliLabelType(Integer mliLabelType) {
        this.mliLabelType = mliLabelType;
    }
}