package com.cesgroup.prison.zbgl.mbsz.service;

import java.util.List;
import java.util.Map;

/**
 * @author zhu.wenjian
 * @time 2021/12/21  13:25
 */
public interface AutoGenerateDutyOrderService {
    Map<String, List<Map<String, Object>>> generate(String mojStartDate, String mojEndDate);
}
