package com.cesgroup.prison.sporadicFlow.entity;

import com.cesgroup.framework.base.entity.StringIDEntity;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * @projectName：prison
 * @ClassName：SporadicFlowRegisterEntity
 * @Description：   零星活动关联罪犯人员表
 * @author：Tao.xu
 * @date：2018年5月25日
 * @version
 */
@Entity
@Table(name = "CDS_SPORADIC_FLOW_PEOPLE_REGISTER")
public class SporadicFlowPeopleRegisterEntity extends StringIDEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_CUSNUMBER
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    private String sprCusnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    private String sprPeopleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    private String sprPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_TYPE
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    private String sprPeopleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_REGISTER_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    private String sprRegisterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_TIME
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    @NotNull
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date sprCrteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_USER_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    private String sprCrteUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_TIME
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    @NotNull
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date sprUpdtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_USER_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    private String sprUpdtUserId;


    private  String sprJSH;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_CUSNUMBER
     *
     * @return the value of CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_CUSNUMBER
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public String getSprCusnumber() {
        return sprCusnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_CUSNUMBER
     *
     * @param sprCusnumber the value for CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_CUSNUMBER
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public void setSprCusnumber(String sprCusnumber) {
        this.sprCusnumber = sprCusnumber == null ? null : sprCusnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_ID
     *
     * @return the value of CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public String getSprPeopleId() {
        return sprPeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_ID
     *
     * @param sprPeopleId the value for CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public void setSprPeopleId(String sprPeopleId) {
        this.sprPeopleId = sprPeopleId == null ? null : sprPeopleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE
     *
     * @return the value of CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public String getSprPeople() {
        return sprPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE
     *
     * @param sprPeople the value for CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public void setSprPeople(String sprPeople) {
        this.sprPeople = sprPeople == null ? null : sprPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_TYPE
     *
     * @return the value of CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_TYPE
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public String getSprPeopleType() {
        return sprPeopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_TYPE
     *
     * @param sprPeopleType the value for CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_PEOPLE_TYPE
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public void setSprPeopleType(String sprPeopleType) {
        this.sprPeopleType = sprPeopleType == null ? null : sprPeopleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_REGISTER_ID
     *
     * @return the value of CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_REGISTER_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public String getSprRegisterId() {
        return sprRegisterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_REGISTER_ID
     *
     * @param sprRegisterId the value for CDS_SPORADIC_FLOW_PEOPLE_REGISTER.SPR_REGISTER_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public void setSprRegisterId(String sprRegisterId) {
        this.sprRegisterId = sprRegisterId == null ? null : sprRegisterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_TIME
     *
     * @return the value of CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_TIME
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    @NotNull
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getSprCrteTime() {
        return sprCrteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_TIME
     *
     * @param ppiCrteTime the value for CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_TIME
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public void setSprCrteTime(Date sprCrteTime) {
        this.sprCrteTime = sprCrteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_USER_ID
     *
     * @return the value of CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_USER_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public String getSprCrteUserId() {
        return sprCrteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_USER_ID
     *
     * @param sprCrteUserId the value for CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_CRTE_USER_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public void setSprCrteUserId(String sprCrteUserId) {
        this.sprCrteUserId = sprCrteUserId == null ? null : sprCrteUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_TIME
     *
     * @return the value of CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_TIME
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    @NotNull
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getSprUpdtTime() {
        return sprUpdtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_TIME
     *
     * @param sprUpdtTime the value for CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_TIME
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public void setSprUpdtTime(Date sprUpdtTime) {
        this.sprUpdtTime = sprUpdtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_USER_ID
     *
     * @return the value of CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_USER_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public String getSprUpdtUserId() {
        return sprUpdtUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_USER_ID
     *
     * @param sprUpdtUserId the value for CDS_SPORADIC_FLOW_PEOPLE_REGISTER.PPI_UPDT_USER_ID
     *
     * @mbggenerated Fri May 25 20:48:24 CST 2018
     */
    public void setSprUpdtUserId(String sprUpdtUserId) {
        this.sprUpdtUserId = sprUpdtUserId == null ? null : sprUpdtUserId.trim();
    }

    public String getSprJSH() {
        return sprJSH;
    }

    public void setSprJSH(String sprJSH) {
        this.sprJSH = sprJSH == null ? null : sprJSH.trim();
    }
}