package com.cesgroup.prison.zbgl.mbsz.service.impl;

import com.cesgroup.prison.common.bean.user.UserBean;
import com.cesgroup.prison.common.facade.AuthSystemFacade;
import com.cesgroup.prison.zbgl.mbsz.service.AutoGenerateDutyOrderService;
import com.cesgroup.prison.zbgl.rlwh.dao.ZbRlwhMapper;
import com.cesgroup.prison.zbgl.rlwh.entity.ZbRlwhEntity;
import com.cesgroup.prison.zbgl.rygl.dao.RyglMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author zhu.wenjian
 * @time 2021/12/21  13:26
 */
@Service
public class AutoGenerateDutyOrderServiceImpl implements AutoGenerateDutyOrderService {

    private static final String ZHZ = "指挥长";
    private static final String WZBZ = "女值班长";
    private static final String MZBZ = "男值班长";
    private static final String WZBY = "女值班员";
    private static final String MZBY = "男值班员";

    @Resource
    private RyglMapper ryglMapper;

    @Resource
    private ZbRlwhMapper zbRlwhMapper;


    @Override
    public Map<String, List<Map<String, Object>>> generate(String mojStartDate, String mojEndDate) {
        UserBean user = AuthSystemFacade.getLoginUserInfo();
        Map<String, List<Map<String,Object>>> reslutMap = new HashMap<>();
        //计算天数
        List<Map<String, Object>> orderData = new ArrayList<>();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String cusNumber = user.getCusNumber();

        List<ZbRlwhEntity> byDateBetween = zbRlwhMapper.findByDateBetween(mojStartDate, mojEndDate);



        return null;
    }




    public class PoliceSelector {

        private String job;

        private int index;

        public PoliceSelector(String job) {
            this.job = job;
        }
    }



}
